import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./components/cart-view/CartContext";
import { NavBarProvider } from "./components/main-view/NavBarContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon: "/Cart.jpg",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <NavBarProvider>
        <CartProvider>
        {children}
        </CartProvider>
      </NavBarProvider>
      </body>
    </html>
  );
}
